# builds docker containers
version: '3'
services:
  # build the app service container from a docker file
  app:
    container_name: docker-node-mongo
    restart: always
    # look in the currect directory for the dockerfile to build the image
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  #  pull down from docker hub the mongo container
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

